language: python

python:
  - "3.6"
  - "3.6-dev"

script:
  - make lint
  - make check-types
  - pip install -r requirements/prod.txt
  - pip install -r requirements/dev.txt
  - PYTHONPATH=$PYTHONPATH:. coverage run --source httpmeter --branch pytest -s tests
  - coverage report -m

after_success:
  - pyenv/bin/coveralls
